### ISSUE TITLE
Add the info for increasing Docker Resources into ReadMe for preparation steps

### ISSUE THREAD

**Issue by NanisTe** [graphaware/hume-nodes2020#1]
I had some issue in the workshop with crashing neo4j instance since my resources for Docker where too small. I would suggest to include the necessary steps to check and adjust the Docker resources, since this is impracticle to do during the workshop and people loose track.

Thanks for this very nice workshop anyways.

**Comment by xdelox** [comment]
Hi @NanisTe, thanks for your suggestion: we've just added some recommendation, useful to avoid this kind of problems in the future. 
Please feel free to contact us in case of further issues.
